version: 0.1

phases:
  build:
    commands:
        - npm install
        - npm run build
artifacts:
  files:
        - '**/*' # all files on github
  base-directory: build # only upload build/* files to s3 bucket
